# -*- coding: utf-8 -*-
"""Data_cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n0MYpl8OQQJKz4vYG1-LvgF0Z9SOiQnC

#Import Libraries
"""

import pandas as pd
import numpy as np

"""#Load Dataset"""

df = pd.read_excel("datasetforcleaning.xlsx")

"""View Dataset"""

df.head()

"""Checking dataset info"""

df.info()

"""#Check missing values"""

df.isnull().sum()

"""#Check duplicate rows"""

df.duplicated().sum()

"""#Check duplicate orderids"""

df["OrderID"].duplicated().sum()

df.drop_duplicates(inplace=True)

df["Date"] = pd.to_datetime(df["Date"])

df["Date"].dtype

df["Product"] = df["Product"].str.title().str.strip()

df["PaymentMethod"] = df["PaymentMethod"].str.title().str.strip()

df["OrderStatus"] = df["OrderStatus"].str.title().str.strip()

df[["Quantity","UnitPrice","TotalPrice"]].dtypes

df["Quantity"] = pd.to_numeric(df["Quantity"])
df["UnitPrice"] = pd.to_numeric(df["UnitPrice"])
df["TotalPrice"] = pd.to_numeric(df["TotalPrice"])

df.isnull().sum()

df["CouponCode"].fillna("No Coupon", inplace=True)

df.isnull().sum()

df.duplicated().sum()

df["OrderID"].duplicated().sum()

df.to_csv("cleaned_dataset.csv", index=False)